"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";

export default function ThumbnailCreator(){
  const canvasRef=useRef<HTMLCanvasElement>(null); const inputRef=useRef<HTMLInputElement>(null); const imageRef=useRef<HTMLImageElement|null>(null);
  const [text,setText]=useState("YOUR BIG IDEA"); const [subtext,setSubtext]=useState("WATCH NOW"); const [color,setColor]=useState("#ffffff"); const [accent,setAccent]=useState("#ff6719"); const [fontSize,setFontSize]=useState(92); const [align,setAlign]=useState<"left"|"center"|"right">("left"); const [brightness,setBrightness]=useState(85); const [zoom,setZoom]=useState(100); const [bg,setBg]=useState("#1b1d20"); const [imageName,setImageName]=useState("");
  const draw=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d")!;ctx.fillStyle=bg;ctx.fillRect(0,0,c.width,c.height);if(imageRef.current){const img=imageRef.current;ctx.save();ctx.filter=`brightness(${brightness}%)`;const scale=Math.max(c.width/img.width,c.height/img.height)*(zoom/100);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);ctx.restore();ctx.fillStyle="rgba(0,0,0,.18)";ctx.fillRect(0,0,c.width,c.height)}const x=align==="left"?70:align==="center"?c.width/2:c.width-70;ctx.textAlign=align;ctx.textBaseline="middle";ctx.font=`900 ${fontSize}px Arial`;ctx.lineWidth=15;ctx.strokeStyle="rgba(0,0,0,.75)";const lines=text.toUpperCase().split("\n");lines.forEach((line,i)=>{const y=c.height/2+(i-(lines.length-1)/2)*(fontSize*1.05)-30;ctx.strokeText(line,x,y);ctx.fillStyle=color;ctx.fillText(line,x,y)});ctx.font="800 32px Arial";ctx.fillStyle=accent;ctx.fillRect(x-(align==="left"?0:align==="center"?150:300),c.height-105,300,48);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.fillText(subtext.toUpperCase(),x+(align==="left"?150:align==="center"?0:-150),c.height-80)};
  useEffect(draw,[text,subtext,color,accent,fontSize,align,brightness,zoom,bg]);
  const upload=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setImageName(file.name);const img=new Image();img.onload=()=>{imageRef.current=img;draw()};img.src=URL.createObjectURL(file)};
  const exportPng=()=>{const a=document.createElement("a");a.download="solara-thumbnail.png";a.href=canvasRef.current!.toDataURL("image/png");a.click()};
  return <main className="thumb-app"><header className="thumb-top"><a href="/dashboard"><span>✦</span>SOLARA</a><div><b>Thumbnail Creator</b><small>Untitled design · Saved locally</small></div><button onClick={exportPng}>Export PNG ↗</button></header><div className="thumb-menu"><button>File</button><button>Edit</button><button>Image</button><button>Layer</button><button>Type</button><span/><button onClick={()=>setText("YOUR BIG IDEA")}>↶ Reset</button></div><section className="thumb-workspace"><aside className="thumb-tools"><button className="active">↖<small>Move</small></button><button onClick={()=>inputRef.current?.click()}>▧<small>Image</small></button><button>T<small>Text</small></button><button>▱<small>Shape</small></button><button>◐<small>Adjust</small></button></aside><aside className="thumb-assets"><h2>Design</h2><button className="upload-image" onClick={()=>inputRef.current?.click()}>＋ Upload image</button><input ref={inputRef} type="file" accept="image/*" hidden onChange={upload}/><p className="thumb-label">CANVAS</p><div className="canvas-size"><b>YouTube Thumbnail</b><small>1280 × 720 px</small></div><p className="thumb-label">TEXT LAYERS</p><label>Headline<textarea value={text} onChange={e=>setText(e.target.value)} rows={3}/></label><label>Badge text<input value={subtext} onChange={e=>setSubtext(e.target.value)}/></label><div className="format-row"><label>Size<input type="number" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></label><label>Text<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>Accent<input type="color" value={accent} onChange={e=>setAccent(e.target.value)}/></label></div><div className="align-row"><button onClick={()=>setAlign("left")}>≡</button><button onClick={()=>setAlign("center")}>≣</button><button onClick={()=>setAlign("right")}>≡</button></div><p className="thumb-label">IMAGE</p><label className="range-label">Brightness <b>{brightness}%</b><input type="range" min="30" max="140" value={brightness} onChange={e=>setBrightness(+e.target.value)}/></label><label className="range-label">Zoom <b>{zoom}%</b><input type="range" min="80" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>Background<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></aside><div className="thumb-stage"><div className="canvas-wrap"><canvas ref={canvasRef} width="1280" height="720"/></div><div className="zoom-status">50% · 1280 × 720</div></div><aside className="layers-panel"><h3>Layers</h3><div className="layer active"><span>T</span><div><b>{text.split("\n")[0]}</b><small>Text</small></div><i>◉</i></div><div className="layer"><span>T</span><div><b>{subtext}</b><small>Text</small></div><i>◉</i></div><div className="layer"><span>▧</span><div><b>{imageName||"Background"}</b><small>Image</small></div><i>◉</i></div><button className="add-layer">＋ Add layer</button></aside></section></main>;
}
